sudo: required
services:
  - docker
before_install:
  - docker build -t charu1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true charu1/react-test npm test


after_success:
  - docker build -t charu1/multi-client ./client
  - docker build -t charu1/multi-nging ./nginx  
  - docker build -t charu1/multi-server ./server
  - docker build -t charu1/multi-worker ./worker
# login in to the docker CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push charu1/multi-client
  - docker push charu1/multi-nginx
  - docker push charu1/multi-server
  - docker push charu1/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-866420346258
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY  
     